### ISSUE TITLE
Using themes

### ISSUE THREAD

**Issue by timcdlucas** [sinhrks/ggfortify#10]
Hi,
Love the package.

Maybe I'm just being stupid but can I use themes like I would in typical ggplot?

I'd hope 
autoplot(lm(rnorm(10)~rnorm(10, 2))) +
  theme_bw()

would theme the 4 facets with the black and white theme. This syntax works for autoplot in other cases (e.g. microbenchmark).

**Comment by timcdlucas** [comment]
Just looking again. I think it's just the facets that are stopping the themes from working. You can theme timeseries plots fine.

**Comment by sinhrks** [comment]
Thanks for feedback!

I just thought about this. Because `autoplot.lm` internally uses `grid.arrange` to output different types of plots in a single canvas, we cannot use ggplot2 operators once it is drawn (#11).

I'm considering either way. Your suggestion is highly appreciated. 

- Add option to return raw `ggplot` instance as `list`. Then, we can perform whatever operation against each `ggplot` instances.
- Allow to use function callback for each `ggplot` instance in `autoplot.lm`, before calling `grid.arrange`.

**Comment by sinhrks** [comment]
Found 3rd option, and I think this is better.

- Create a simple container and make grids behave as the same as single ggplot.

**Comment by sinhrks** [comment]
I think #12 should work, pls check.
