### ISSUE TITLE
Ability to turn off points in plots to just show text labels

### ISSUE THREAD

**Issue by abresler** [sinhrks/ggfortify#22]
Maybe good to add a plotting parameter that allows you to turn off points to just show labels in factor plots if there isn't already a way to do this.

**Comment by sinhrks** [comment]
Thanks for feedback. How about using ``shape`` attribute to control them? I've did very rough implementation in #24, and will continue to work once it looks OK.

- http://sape.inf.usi.ch/quick-reference/ggplot2/shape

To disable points, specify `shape=FALSE`. In this case, ``label`` is automatically turned on unless otherwise specified.
```
autoplot(stats::prcomp(USArrests), shape=FALSE)
```
![rplot01](https://cloud.githubusercontent.com/assets/1696302/6146587/c538883c-b231-11e4-87be-0cc19b8e8b0a.png)

You can pass column name via ``shape``.
```
autoplot(stats::prcomp(iris[-5]), data = iris, shape='Species')
```
![rplot02](https://cloud.githubusercontent.com/assets/1696302/6146588/c9628d5e-b231-11e4-9428-54285d9009a5.png)

```
autoplot(stats::prcomp(iris[-5]), data = iris, shape=FALSE, label.colour='Species')
```
![rplot03](https://cloud.githubusercontent.com/assets/1696302/6146589/cdc87200-b231-11e4-92f9-7844f57fe59d.png)

**Comment by abresler** [comment]
Fantastic!

-- 
Alex Bresler

ASBC LLLC
asbcllc.com
917-455-0239

abresler@asbcllc.com
@abresler

**Comment by sinhrks** [comment]
Done in #24. Also updated the docs. Pls check :D

- http://rpubs.com/sinhrks/plot_pca
- http://rpubs.com/sinhrks/plot_lm
